spring.application.name=BTTH12

# Static resources configuration
spring.web.resources.static-locations=classpath:/static/
spring.mvc.static-path-pattern=/**

# WebSocket configuration
server.servlet.context-path=/